export enum DISTRICT {
    LEILEK,
    NOOKAT,
    KADAMJAI,
    BATKEN,
    TALAS,
    CHUY,
    NARYN,
    JETI_OGUZ,
    AK_SUU,
    TON,
    YSSYK_KOL,
    ARAVAN,
    CHON_ALAI,
    ALAI,
    KARA_SUU,
    KARA_KULJA,
    OZGON,
    ALAMUDUN,
    MOSKVA,
    PONFILOV,
    JAIYL,
    KEMIN,
    YSSYK_ATA,
    SOKULUK,
    AITMATOV,
    BAKAI_ATA,
    MANAS,
    AKSY,
    NOOKEN,
    TOKTOGUL,
    SUZAK,
    ALA_BUKA,
    BAZAR_KORGON,
    TOGUZ_TORO,
    CHATKAL,
    JUMGAL,
    AK_TALAA,
    AT_BASHY,
    KOCHKOR,
    TUP,
    ISLAND = 'ISLAND',
}

export enum REGIONS {
    CHUY = 'CHUY',
    TALAS = 'TALAS',
    OSH = 'OSH',
    OSH_CITY = 'OSH_CITY',
    BISHKEK = 'BISHKEK',
    BATKEN = 'BATKEN',
    JALAL_ABAD = 'JALAL_ABAD',
    NARYN = 'NARYN',
    YSSYK_KOL = 'YSSYK_KOL',
}

export type RegionsType = keyof typeof REGIONS
export type DistrictType = keyof typeof DISTRICT
